= Accessing the {openshift} web console

Access the {ocp} web console by using your web browser.

Access the cluster by using either the `kubeadmin` or `developer` user.
Use the `developer` user for creating projects or {openshift} applications and for application deployment.
Use the `kubeadmin` user only for administrative tasks such as creating new users or setting roles.

.Prerequisites
* {prod} is configured to use the {openshift} preset.
For more information, see xref:changing-the-selected-preset.adoc[].
* A running {prod} instance.
For more information, see xref:starting-the-instance.adoc[].

.Procedure
. To access the {ocp} web console with your default web browser, run the following command:
+
[subs="+quotes,attributes"]
----
$ {bin} console
----

. Log in as the `developer` user with the password printed in the output of the [command]`{bin} start` command.
You can also view the password for the `developer` and `kubeadmin` users by running the following command:
+
[subs="+quotes,attributes"]
----
$ {bin} console --credentials
----

See xref:troubleshooting.adoc[] if you cannot access the {ocp} cluster managed by {prod}.

.Additional resources
* The link:https://docs.openshift.com/container-platform/latest/applications/projects/working-with-projects.html[{ocp} documentation] covers the creation of projects and applications.
